name: vdiff
description: Run your vdiff tests, upload a report and open a PR with the new goldens as necessary
inputs:
  AWS_ACCESS_KEY_ID:
    description: Access key id for the role that will assume the vdiff role
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: Access key secret for the role that will assume the vdiff role
    required: true
  AWS_SESSION_TOKEN:
    description: Session token for the role that will assume the vdiff role
    required: true
  GITHUB_TOKEN:
    description: Token used to cleanup branches and open the goldens PR
    required: true
  TEST_CHROME:
    description: Run vdiff tests in Chromium
    default: true
  TEST_FILES:
    description: Pattern of vdiff tests to run
    default: './test/**/*.vdiff.js'
  TEST_FIREFOX:
    description: Run vdiff tests in Firefox
    default: false
  TEST_SAFARI:
    description: Run vdiff tests in Webkit
    default: false
  TEST_TIMEOUT:
    description: Timeout threshold for vdiff tests (in ms)
    default: 40000
  VDIFF_BRANCH_PREFIX:
    description: Prefix for vdiff branches
    default: 'ghworkflow/vdiff'
runs:
  using: composite
  steps:
    - name: Get Run Info
      id: run-info
      run: |
        echo -e "\e[34mGetting Run Info"
        if [ ${{ github.event.number }} ]; then
          ORIGINAL_SHA=${{ github.event.pull_request.head.sha }}
        else
          ORIGINAL_SHA=${GITHUB_SHA}
        fi
        echo "original-sha=${ORIGINAL_SHA}" >> ${GITHUB_OUTPUT}
      env:
        FORCE_COLOR: 3
      shell: bash

    - name: vdiff Branch Cleanup
      uses: Brightspace/third-party-actions@actions/github-script
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          console.log('\x1b[34mCleaning Up Orphaned vdiff Branches');
          const branchPrefix = `${process.env.PREFIX}-pr-`;

          const vdiffBranches = await github.rest.git.listMatchingRefs({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `heads/${branchPrefix}`
          });

          for (let i = 0; i < vdiffBranches.data.length; i++) {
            const branch = vdiffBranches.data[i].ref;
            const prNum = branch.slice(branch.lastIndexOf('-') + 1);

            let prInfo,
              prOpen = true;
            try {
              prInfo = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNum
              });
        
              if (prInfo.data.state !== 'open') {
                prOpen = false;
              }
            } catch (e) {
              console.log(`\x1b[31m${e}`);
              console.log(`\x1b[31mCould not get details for PR #${prNum} - skipping branch ${branch}.`);
              continue;
            }

            if (!prOpen) {
              console.log(`PR #${prNum} is no longer open - deleting branch ${branch}.\n`);
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: branch.substring(5)
                });
              } catch (e) {
                console.log(`\x1b[31m${e}`);
                console.log(`\x1b[31mCould not delete branch ${branch}.`);
              }
            }
          }
          console.log('Done processing vdiff branches.\n');
      env:
        FORCE_COLOR: 3
        PREFIX: ${{ inputs.VDIFF_BRANCH_PREFIX }}

    - name: Move Current Goldens
      run: |
        echo -e "\e[34mMoving Current Goldens to .vdiff"
        echo "Clearing .vdiff directory"
        rm -rf .vdiff

        echo "Moving current goldens to .vdiff directory"
        find . -name golden -type d | while read GOLDEN_DIR; do
          TEST_PATH=`dirname "${GOLDEN_DIR}"`
          TEST_PATH=${TEST_PATH:2}
          for TEST in `ls "${GOLDEN_DIR}"`; do
            mkdir -p "./.vdiff/${TEST_PATH}/${TEST}/golden"
            mv "${GOLDEN_DIR}/${TEST}/"* "./.vdiff/${TEST_PATH}/${TEST}/golden"
          done
        done
      env:
        FORCE_COLOR: 3
      shell: bash

    - name: Run vdiff Tests
      id: test-run
      run: |
        echo -e "\e[34mRunning vdiff Tests"
        if [ ${CHROME} == true ]; then BROWSERS="--chrome "; fi
        if [ ${FIREFOX} == true ]; then BROWSERS="${BROWSERS}--firefox "; fi
        if [ ${SAFARI} == true ]; then BROWSERS="${BROWSERS}--safari"; fi

        echo ${BROWSERS}
        npx d2l-test-runner vdiff --files ${FILES} --timeout ${TIMEOUT} ${BROWSERS} && echo "passed=true" >> ${GITHUB_OUTPUT} || echo "passed=false" >> ${GITHUB_OUTPUT}
      env:
        CHROME: ${{ inputs.TEST_CHROME }}
        FILES: ${{ inputs.TEST_FILES }}
        FIREFOX: ${{ inputs.TEST_FIREFOX }}
        FORCE_COLOR: 3
        SAFARI: ${{ inputs.TEST_SAFARI }}
        TIMEOUT: ${{ inputs.TEST_TIMEOUT }}
      shell: bash

    - name: Prepare Report
      id: prepare-report
      if: ${{ inputs.AWS_ACCESS_KEY_ID }}
      continue-on-error: true
      run: |
        echo -e "\e[34mPreparing vdiff Report"
        mv "./.vdiff/.report/" "./.vdiff/report/"

        DATE_TIME=$(date '+%Y-%m-%d_%H-%M-%S');
        UPLOAD_PATH="${{ github.repository }}/${ORIGINAL_SHA}/${DATE_TIME}"
        echo "upload-path=${UPLOAD_PATH}" >> ${GITHUB_OUTPUT}
      env:
        FORCE_COLOR: 3
        ORIGINAL_SHA: ${{ steps.run-info.outputs.original-sha }}
      shell: bash

    - name: Assume vdiff Role for Uploading Report
      if: ${{ inputs.AWS_ACCESS_KEY_ID }}
      continue-on-error: true
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ inputs.AWS_SESSION_TOKEN }}
        role-to-assume: "arn:aws:iam::037018655140:role/visual-diff-githubactions-access"
        role-duration-seconds: 3600
        aws-region: ca-central-1

    - name: Upload Report
      id: upload-report
      if: ${{ inputs.AWS_ACCESS_KEY_ID }}
      continue-on-error: true
      uses: BrightspaceUI/actions/publish-to-s3@main
      with:
        BUCKET_PATH: s3://visual-diff.d2l.dev/reports/${{ steps.prepare-report.outputs.upload-path }}/
        CACHE_DEFAULT: "--cache-control max-age=120"
        PUBLISH_DIRECTORY: ./.vdiff/

    - name: Move New Goldens
      run: |
        echo -e "\e[34mMoving New Goldens to Proper Directories"

        echo "Moving passed screenshots back to golden directories"
        find ./.vdiff -name pass -type d | while read PASS_DIR; do
          DIR=`dirname "${PASS_DIR}"`
          TEST_PATH=`dirname "${DIR}"`
          TEST_PATH=${TEST_PATH:9}
          TEST=`basename "${DIR}"`

          mkdir -p "./${TEST_PATH}/golden/${TEST}"
          mv "${PASS_DIR}/"* "./${TEST_PATH}/golden/${TEST}"    
        done
        
        echo "Moving failed screenshots to golden directories"
        find ./.vdiff -name fail -type d | while read FAIL_DIR; do
          DIR=`dirname "${FAIL_DIR}"`
          TEST_PATH=`dirname "${DIR}"`
          TEST_PATH=${TEST_PATH:9}
          TEST=`basename "${DIR}"`
        
          for BROWSER in `ls "${FAIL_DIR}"`; do
            mkdir -p "./${TEST_PATH}/golden/${TEST}/${BROWSER}"
            for PNG in `ls "${FAIL_DIR}/${BROWSER}"`; do
              NAME=`basename "${PNG}"`
              if  [[ ${NAME} != *"-diff.png" ]] && [[ ${NAME} != *"-resized-golden.png" ]] && [[ ${NAME} != *"-resized-screenshot.png" ]]; then
                mv "${FAIL_DIR}/${BROWSER}/${PNG}" "./${TEST_PATH}/golden/${TEST}/${BROWSER}/${PNG}"
              fi
            done
          done
        done

        echo "Clearing .vdiff directory"
        rm -rf .vdiff
      env:
        FORCE_COLOR: 3
      shell: bash
