name: Commit Changes
outputs:
  diff:
    description: "Whether there were any changes to commit"
    value: ${{ steps.commit-changes.outputs.diff }}
inputs:
  original-sha:
    description: "The SHA of the original commit"
  source-branch:
    description: "The branch to commit changes to"
  t9n-branch:
    description: "The branch to commit changes from"
  change-type:
    description: "The type of change being made"

runs:
  using: composite
  steps:
  - id: commit-changes
    run: |
      echo -e "\e[34mCommitting translation changes (if necessary)"
      if git diff --quiet; then
        echo -e "\e[32m - no changes needed.\n"
        exit 0;
      fi
      echo -e "\e[31mChanges made - committing"

      if ! git diff --quiet ${ORIGINAL_SHA}; then
        echo "diff=true" >> ${GITHUB_OUTPUT}
      else
        echo "diff=false" >> ${GITHUB_OUTPUT}
      fi

      echo -e "\n\e[34mCreating the Translation Branch"
      git stash --include-untracked
      git fetch origin +refs/heads/${SOURCE_BRANCH}:refs/heads/${SOURCE_BRANCH} -q -u || true
      git checkout ${SOURCE_BRANCH}
      if [ $(git rev-parse HEAD) != ${ORIGINAL_SHA} ]; then
        echo -e "\e[31mBranch out of date - more commits have been added to the '${SOURCE_BRANCH}' branch since this action started running.  Stopping this formatting run."
        exit 1;
      fi

      git checkout ${T9N_BRANCH} || git checkout -b ${T9N_BRANCH}

      echo "empty=false" >> ${GITHUB_OUTPUT}
      echo "conflict=false" >> ${GITHUB_OUTPUT}
      if [ $(git stash list | wc -l) == 0 ]; then
        echo -e "\e[31mNo changes to apply - please see errors above."
        echo "empty=true" >> ${GITHUB_OUTPUT}
        exit 0;
      fi
      if ! git stash apply; then
        echo -e "\e[31mCould not apply stash - merge conflicts with ${{ github.event.pull_request.base.ref }}."
        echo "conflict=true" >> ${GITHUB_OUTPUT}
        exit 0;
      fi

      echo -e "\n\e[34mCommitting translation changes"
      git config user.name github-actions[bot]
      git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      git reset HEAD
      git add -u
      git commit -m "Updating translations - ${CHANGE_TYPE}"

      echo -e "\n\e[34mPushing the Translation Branch"
      git push --force origin ${T9N_BRANCH}
    env:
      FORCE_COLOR: 3
      ORIGINAL_SHA: ${{ inputs.original-sha }}
      SOURCE_BRANCH: ${{ inputs.source-branch }}
      T9N_BRANCH: ${{ inputs.t9n-branch }}
      CHANGE_TYPE: ${{ inputs.change-type }}
    shell: bash
