name: Visual Diff
description: Run your visual diff tests and open a PR with the new goldens as necessary
inputs:
  AWS_ACCESS_KEY_ID:
    description: Access key id for the role that will assume the visual diff role
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: Access key secret for the role that will assume the visual diff role
    required: true
  AWS_SESSION_TOKEN:
    description: Session token for the role that will assume the visual diff role
    required: true
  DRAFT_PR:
    description: Whether to open the goldens PR as a draft PR
    default: true
  GITHUB_TOKEN:
    description: Token to use to open the goldens PR
    required: true
  TEST_PATH:
    description: Path passed into the mocha call defining the locations and name structure of the tests
    default: './{,!(node_modules)/**}/*.visual-diff.js'
  TEST_TIMEOUT:
    description: Test timeout passed into the mocha call
    default: 40000
runs:
  using: composite
  steps:
    - name: Install Dependencies
      run: |
        echo -e "\e[34mInstalling Dependencies"
        NPM_PACKAGE=$(cut -d "=" -f 2 <<< $(npm run env | grep "npm_package_name"))
        if [ $NPM_PACKAGE != '@brightspace-ui/visual-diff' ]; then
          npm install mocha@9 puppeteer@12 @brightspace-ui/visual-diff@7 --no-save
        fi
        npm install chalk@5 @octokit/rest@18 --prefix ${{ github.action_path }} --no-save --loglevel error
      env:
        FORCE_COLOR: 3
      shell: bash
    - name: Visual Diff Branch Cleanup
      run: |
        echo -e "\e[34mCleaning Up Orphaned Visual Diff Branches"
        node ${{ github.action_path }}/cleanup-branches.js
      env:
        FORCE_COLOR: 3
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        VISUAL_DIFF_BRANCH_PREFIX: 'ghworkflow/visual-diff-pr-'
      shell: bash
    - name: Running Visual Diff Tests
      id: visual-diff-tests
      run: |
        echo -e "\e[34mRunning Visual Diff Tests"
        npx mocha '${{ inputs.TEST_PATH }}' -t ${{ inputs.TEST_TIMEOUT }} --colors --require esm && echo "::set-output name=tests-passed::$(echo true)" || echo "::set-output name=tests-passed::$(echo false)"
        if [ -f failed-reports.txt ]; then
          FAILED_REPORTS=$(<failed-reports.txt)
          echo "::set-output name=failed-reports::$(echo "$FAILED_REPORTS")"
          rm failed-reports.txt
        fi
      env:
        FORCE_COLOR: 3
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ inputs.AWS_SESSION_TOKEN }}
      shell: bash
    - name: Committing the New Goldens (if necessary)
      id: committing-goldens
      run: |
        if [ ${{ github.event.number }} ]; then
          SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}
          VISUAL_DIFF_BRANCH=ghworkflow/visual-diff-pr-${{ github.event.number }}
          ORIGINAL_SHA=${{ github.event.pull_request.head.sha }}
        else
          SOURCE_BRANCH=${GITHUB_REF#refs/heads/}
          VISUAL_DIFF_BRANCH=ghworkflow/visual-diff-${GITHUB_REF#refs/heads/}
          ORIGINAL_SHA=$GITHUB_SHA
        fi
        echo "::set-output name=source-branch::$(echo "$SOURCE_BRANCH")"
        echo "::set-output name=visual-diff-branch::$(echo "$VISUAL_DIFF_BRANCH")"
      
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} == true ]; then
          echo -e "\e[32mVisual diff tests have passed - no new goldens needed.\n"
          exit 0;
        fi
        echo -e "\e[31mVisual diff tests failed - generating new goldens."
        
        echo -e "\n\e[34mCreating the Visual Diff Branch"
        git stash --include-untracked
        git fetch origin +refs/heads/$SOURCE_BRANCH:refs/heads/$SOURCE_BRANCH -q -u || true
        git checkout $SOURCE_BRANCH
        git checkout -b $VISUAL_DIFF_BRANCH
        if [ $(git rev-parse HEAD) != $ORIGINAL_SHA ]; then
          echo -e "\e[31mBranch out of date - more commits have been added to the '$SOURCE_BRANCH' branch since this action started running.  Stopping this test run."
          exit 1;
        fi
        
        echo "::set-output name=changes-empty::$(echo false)"
        echo "::set-output name=goldens-conflict::$(echo false)"
        if [ $(git stash list | wc -l) == 0 ]; then
          echo -e "\e[31mNo changes to apply - please see errors above."
          echo "::set-output name=changes-empty::$(echo true)"
          exit 0;
        fi
        if ! git stash apply; then
          echo -e "\e[31mCould not apply stash - merge conflicts with ${{ github.event.pull_request.base.ref }}."
          echo "::set-output name=goldens-conflict::$(echo true)"
          exit 0;
        fi
        
        echo -e "\n\e[34mCommitting new goldens"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m 'Updating Visual Diff Goldens'
        
        echo -e "\n\e[34mPushing the Visual Diff Branch"
        git push --force origin $VISUAL_DIFF_BRANCH  
      env:
        FORCE_COLOR: 3
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
    - name: Handling the Goldens PR (if necessary)
      run: |   
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} == true ] || [ ${{ steps.committing-goldens.outputs.goldens-conflict }} == true ]; then
          if git ls-remote --exit-code --heads origin $VISUAL_DIFF_BRANCH; then
            echo -e "\e[34mClosing Goldens PR and Deleting Branch"
            git push -d origin $VISUAL_DIFF_BRANCH || true
          fi
        fi
     
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} == true ]; then
          echo -e "\e[32mCompleted - Build Passed."
          exit 0;
        fi
        
        if [ ${{ steps.committing-goldens.outputs.changes-empty }} == true ] || [ ${{ steps.committing-goldens.outputs.goldens-conflict }} == true ]; then
          node ${{ github.action_path }}/handle-issues.js
        else
          node ${{ github.action_path }}/handle-pr.js
        fi
 
        echo -e "\e[31mCompleted - Build Failed."
        exit 1;
      env:
        DRAFT_PR: ${{ inputs.DRAFT_PR }}
        FAILED_REPORTS: ${{ steps.visual-diff-tests.outputs.failed-reports }}
        FORCE_COLOR: 3
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GOLDENS_CONFLICT: ${{ steps.committing-goldens.outputs.goldens-conflict }}
        PULL_REQUEST_NUM: ${{ github.event.number }}
        PULL_REQUEST_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        SOURCE_BRANCH: ${{ steps.committing-goldens.outputs.source-branch }}
        VISUAL_DIFF_BRANCH: ${{ steps.committing-goldens.outputs.visual-diff-branch }}
      shell: bash
