name: Semantic Release
description: Deploy using semantic-release
inputs:
  DEFAULT_BRANCH:
    description: name of the default release branch
    default: main
  DRY_RUN:
    description: Runs semantic-release with the "--dry-run" flag to simulate a release but not actually do one
    default: false
  GITHUB_TOKEN:
    description: Token to use to update version in 'package.json' and create GitHub release
    required: true
  MINOR_RELEASE_WITH_LMS:
    description: Automatically perform a minor release whenever the LMS release changes (requires RALLY_API_KEY)
    default: false
  NPM:
    description: Whether or not to release as an NPM package
    default: false
  NPM_TOKEN:
    description: Token to publish to NPM
  RALLY_API_KEY:
    description: Key to access the Rally API, required for MINOR_RELEASE_WITH_LMS
outputs:
  VERSION:
    description: Version of the new release
    value: ${{ steps.semantic-release.outputs.version }}
runs:
  using: composite
  steps:
    - name: Installing semantic-release
      run: |
        echo "Installing semantic-release..."
        npm install semantic-release@17 @semantic-release/git@9 --no-save
      shell: bash
    - name: Get Repo's Last LMS Release
      if: ${{ inputs.MINOR_RELEASE_WITH_LMS == 'true' }}
      id: repo-lms-version
      run: echo "::set-output name=value::$(cat .lmsrelease)"
      shell: bash
    - name: Get Active LMS Release
      if: ${{ inputs.MINOR_RELEASE_WITH_LMS == 'true' }}
      id: get-lms-version
      uses: Brightspace/lms-version-actions/get-lms-release@main
      with:
        RALLY_API_KEY: ${{ inputs.RALLY_API_KEY }}
    - name: Update Repo's Last LMS Release
      if: ${{ inputs.MINOR_RELEASE_WITH_LMS == 'true' && inputs.DRY_RUN == 'false' && steps.repo-lms-version.outputs.VALUE != steps.get-lms-version.outputs.LMS_VERSION }}
      run: |
        echo "Updating last LMS release..."
        echo "${{ steps.get-lms-version.outputs.LMS_VERSION }}" > .lmsrelease
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .lmsrelease
        git commit -m "feat: updating tracked LMS release version [skip ci]"
        git push --follow-tags --repo=https://$GITHUB_TOKEN@github.com/${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
    - name: Create semantic-release configuration
      run: |
        echo "Creating semantic-release configuration (DEFAULT_BRANCH: ${{ inputs.DEFAULT_BRANCH }} , NPM: ${{ inputs.NPM }})..."
        ${{ github.action_path }}/create-config.sh
      env:
        DEFAULT_BRANCH: ${{ inputs.DEFAULT_BRANCH }}
        FILE_PATH: ${{ github.workspace }}/.releaserc.json
        NPM: ${{ inputs.NPM }}
      shell: bash
    - name: Running semantic-release
      id: semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      run: |
        echo "::set-output name=version::"
        if [ ${{ inputs.DRY_RUN }} == true ]; then
          echo "Running semantic-release (dry run)..."
          npx semantic-release --dry-run
        else
          OLD_VERSION=$(node -p -e "require('./package.json').version")
          echo "Running semantic-release..."
          npx semantic-release
          NEW_VERSION=$(node -p -e "require('./package.json').version")
          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "::set-output name=version::$(echo $NEW_VERSION)"
          fi
        fi
      shell: bash
