name: Publish to CDN
description: Publishes the specified directory to the Brightspace CDN

inputs:
  aws-access-key-id:
    description: The AWS access key ID to use for publishing
    required: true
  aws-secret-access-key:
    description: The AWS secret access key to use for publishing
    required: true
  aws-session-token:
    description: The AWS session token to use for publishing
    required: true
  cdn-path:
    description: The path on the CDN beneath `s3://d2lprodcdn/`, to which to publish
    required: true
  publish-directory:
    description: The directory within your repo to publish to the CDN
    required: true

runs:
  using: composite
  steps:
    - name: Determine Role Name
      id: role-name
      run: |
        ORG_NAME="${{ github.repository_owner }}"
        if [[ ${ORG_NAME} == "BrightspaceHypermediaComponents" ]]; then ORG_NAME="BHC"; fi

        REPO_NAME="${{ github.repository }}"        
        REPO_NAME="${REPO_NAME#*/}"

        echo "value=arn:aws:iam::771734770799:role/r+$ORG_NAME+$REPO_NAME+repo" >> $GITHUB_OUTPUT
      shell: bash
    - name: Assume role
      uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        role-to-assume: "${{ steps.role-name.outputs.value }}"
        role-duration-seconds: 3600
        aws-region: us-east-1
    - name: Overwrite Protection
      run: |
        if [[ $(aws s3 ls "s3://d2lprodcdn/${CDN_PATH}/" | head) ]]; then
           echo "ERROR: cdn-path "\""$CDN_PATH"\"" already exists, which would result in files being overwritten. Choose a unique publish path.";
           exit 1;
        fi
      shell: bash
      env:
        CDN_PATH: ${{ inputs.cdn-path }}
    - name: Deploy
      uses: BrightspaceUI/actions/publish-to-s3@main
      with:
        bucket-path: s3://d2lprodcdn/${{ inputs.cdn-path }}
        cache-default: --cache-control public,max-age=31536000,immutable
        publish-directory: ${{ inputs.publish-directory }}
        public-read: true
    - name: Publish Complete
      run: |
        # Display CDN location
        echo -e "\e[32mFiles available at:\e[0m https://s.brightspace.com/${CDN_PATH}\n"
      shell: bash
      env:
        CDN_PATH: ${{ inputs.cdn-path }}
